### ISSUE TITLE
sqlStatement too long during planet import..

### ISSUE THREAD

**Issue by thsc42** [OpenHistoricalDataMap/OSMImportUpdate#2]
Happend while importing relations into intermediate db.
Apparently, the sql statement was too long in exec.

OK, that import variant shall be replaced by dump import.
Anayway, it can cause problems also in inter2ohdm import.
Check max length of an sql statement for prepareStatement.

Also: Check when an exec thread is created from sql queue.

That's the tail of the err log of import ended 2017, Jan, 16th.

import from osm file into intermediate db
Exception in thread "Thread-446720582" java.lang.ArrayIndexOutOfBoundsException
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:597
)
        at java.lang.StringBuilder.append(StringBuilder.java:190)
        at org.postgresql.core.Parser.parseSql(Parser.java:1026)
        at org.postgresql.core.Parser.replaceProcessing(Parser.java:972)
        at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateA
ction.java:41)
        at org.postgresql.core.CachedQueryCreateAction.create(CachedQueryCreateA
ction.java:17)
        at org.postgresql.util.LruCache.borrow(LruCache.java:115)
        at org.postgresql.core.QueryExecutorBase.borrowQuery(QueryExecutorBase.j
ava:266)
        at org.postgresql.jdbc.PgConnection.borrowQuery(PgConnection.java:143)
        at org.postgresql.jdbc.PgPreparedStatement.<init>(PgPreparedStatement.ja
va:88)
        at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1
256)
        at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1
622)
        at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:4
15)
        at util.SQLExecute.doExec(SQLExecute.java:41)
        at util.SQLExecute.run(SQLExecute.java:62)

**Comment by thsc42** [comment]
added a couldExecute to member sql queue whenever a new member was found in OSM file. Should work. Test is running.. revision 252 with max buffer len 1 byte. (increased max buffer len to 100 bytes in revision 254. That should works well.)

**Comment by thsc42** [comment]
That caused the problem:
INSERT INTO planet.relationmember (relation_id, role,  node_id)  VALUES ( 172045, 'Addenbrooke's', 533796734);  Was that simple. We have to quote ' inside an already quoted string.

**Comment by thsc42** [comment]
test started with rev 258 started June 28. Cross fingers :)

**Comment by thsc42** [comment]
done. revision 258 did it after nearly 4 days( 3 days and 23 hours)
